[package]
name = "truetype"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/bodoni/truetype"
homepage = "https://github.com/bodoni/truetype"
description = "The package provides a parser for TrueType fonts."
