[package]
name = "truetype"
version = "0.26.1"
license = "Apache-2.0/MIT"
authors = [
    "Ivan Ukhov <ivan.ukhov@gmail.com>",
    "Vladimir Vukicevic <vladimir@pobox.com>",
]
description = "The package provides a parser for TrueType fonts."
documentation = "https://docs.rs/truetype"
homepage = "https://github.com/bodoni/truetype"
repository = "https://github.com/bodoni/truetype"
categories = ["parsing"]
keywords = ["font", "truetype", "typeface", "typography"]
exclude = ["tests/fixtures/*"]
